version: "3.7"

services:
  caddy:
    image: zhuxia/caddy:2.3.0-rc.1
    container_name: caddy2-test
    restart: always
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
      - "127.0.0.1:2019:2019"
    volumes:
      - ./data:/data
      - ./config:/etc/caddy
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    sysctls:
        net.core.rmem_max: 2500000
