FROM golang:1.22-alpine3.20 AS builder

RUN apk add --no-cache \
    ca-certificates \
    git \
    libcap

WORKDIR /build

ENV XCADDY_VERSION v0.4.2
# Configures xcaddy to build with this version of Caddy
ENV CADDY_VERSION v2.8.4
# Configures xcaddy to not clean up post-build (unnecessary in a container)
ENV XCADDY_SKIP_CLEANUP 1
# Sets capabilities for output caddy binary to be able to bind to privileged ports
ENV XCADDY_SETCAP 1

RUN set -eux; \
    go install github.com/caddyserver/xcaddy/cmd/xcaddy@${XCADDY_VERSION}; \
    mv ${GOPATH}/bin/xcaddy /usr/bin/xcaddy; \
    chmod +x /usr/bin/xcaddy

RUN xcaddy build ${CADDY_VERSION} \
    --with github.com/ZhangXavier/caddy-dns-cloudflare@995684b4b8776edcef5524d8b6329f56784485c6 \
    --with github.com/caddy-dns/duckdns@77870e12bac552ceb76917d82ced6db84b958c1f \
    --with github.com/hairyhenderson/caddy-teapot-module@0cb03ce7d45ae9282fef62908bb20d75453be1d5 \
    --with github.com/ueffel/caddy-brotli@de4efb4b9d9492075b325b46a29d8e2d79d97902

FROM alpine:3.20

RUN apk add --no-cache \
    ca-certificates \
    libcap \
    mailcap

RUN set -eux; \
    mkdir -p \
        /config/caddy \
        /data/caddy \
        /etc/caddy \
        /usr/share/caddy \
    ; \
    wget -O /etc/caddy/Caddyfile "https://github.com/caddyserver/dist/raw/2f024e8988f98bcfc4e2d9924139ae4914a24e9a/config/Caddyfile"; \
    wget -O /usr/share/caddy/index.html "https://github.com/caddyserver/dist/raw/2f024e8988f98bcfc4e2d9924139ae4914a24e9a/welcome/index.html"

# https://github.com/caddyserver/caddy/releases
ENV CADDY_VERSION v2.8.4

COPY --from=builder /build/caddy /usr/bin/caddy

# See https://caddyserver.com/docs/conventions#file-locations for details
ENV XDG_CONFIG_HOME /config
ENV XDG_DATA_HOME /data

LABEL org.opencontainers.image.version=v2.8.4
LABEL org.opencontainers.image.title=Caddy
LABEL org.opencontainers.image.description="a powerful, enterprise-ready, open source web server with automatic HTTPS written in Go"
LABEL org.opencontainers.image.url=https://caddyserver.com
LABEL org.opencontainers.image.documentation=https://caddyserver.com/docs
LABEL org.opencontainers.image.vendor="Light Code Labs"
LABEL org.opencontainers.image.licenses=Apache-2.0
LABEL org.opencontainers.image.source="https://github.com/ZhangXavier/caddy-docker"

EXPOSE 80
EXPOSE 443
EXPOSE 443/udp
EXPOSE 2019

WORKDIR /srv

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
