name: Build and Publish 2.9 Docker Linux image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
       - '2.9/**'

jobs:
  docker-linux-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push 2.9
        id: docker_build_2_9
        uses: docker/build-push-action@v6
        with:
          context: ./2.9
          file: ./2.9/Dockerfile-alpine
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            zxavier/caddy:latest,zxavier/caddy:mainline,zxavier/caddy:2,zxavier/caddy:2.9,zxavier/caddy:2.9.1
            ghcr.io/zhangxavier/caddy:latest,ghcr.io/zhangxavier/caddy:mainline,ghcr.io/zhangxavier/caddy:2,ghcr.io/zhangxavier/caddy:2.9,ghcr.io/zhangxavier/caddy:2.9.1
      -
         name: Update repo description
         uses: peter-evans/dockerhub-description@v4
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
           repository: zxavier/caddy
