name: Build and Publish nightly Docker Linux image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'
  push:
    branches: [ main ]
    paths: 
       - 'nightly/**'

jobs:
  docker-linux-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push nightly
        id: docker_build_nightly
        uses: docker/build-push-action@v6
        with:
          context: ./nightly
          file: ./nightly/Dockerfile-alpine
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            zxavier/caddy:nightly
            zxavier/caddy:nightly-${{ github.sha }}
            ghcr.io/zhangxavier/caddy:nightly
            ghcr.io/zhangxavier/caddy:nightly-${{ github.sha }}
      -
         name: Update Hub description
         uses: peter-evans/dockerhub-description@v4
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
           repository: zxavier/caddy
